---
abstract: 'Puzzle with Bubbles'
author: []
build_requires:
  Alien::SDL: 1.403
  Data::Dumper: 0
  Errno: 0
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 2.16
  File::Basename: 0
  File::Copy: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  IO::Socket: 1.24
  Locale::Maketext::Extract: 0
  Locale::Maketext::Simple: 0
  Math::Trig: 0
  Module::Build: 0.36
  SDL: 2.405
  Time::HiRes: 0
  autodie: 0
  parent: 0
  perl: 5.008
configure_requires:
  Alien::SDL: 1.403
  Data::Dumper: 0
  Errno: 0
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 2.16
  File::Basename: 0
  File::Copy: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  IO::Socket: 1.24
  Locale::Maketext::Extract: 0
  Locale::Maketext::Simple: 0
  Math::Trig: 0
  Module::Build: 0.36
  SDL: 2.405
  Time::HiRes: 0
  autodie: 0
  parent: 0
  perl: 5.008
dynamic_config: 1
generated_by: 'Module::Build version 0.3603'
license: gpl2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-FrozenBubble
no_index:
  directory:
    - server
provides:
  Games::FrozenBubble:
    file: lib/Games/FrozenBubble.pm
    version: 2.202
  Games::FrozenBubble::CStuff:
    file: lib/Games/FrozenBubble/CStuff.pm
  Games::FrozenBubble::Config:
    file: lib/Games/FrozenBubble/Config.pm
  Games::FrozenBubble::LevelEditor:
    file: lib/Games/FrozenBubble/LevelEditor.pm
  Games::FrozenBubble::MDKCommon:
    file: lib/Games/FrozenBubble/MDKCommon.pm
  Games::FrozenBubble::Net:
    file: lib/Games/FrozenBubble/Net.pm
  Games::FrozenBubble::NetDiscover:
    file: lib/Games/FrozenBubble/NetDiscover.pm
  Games::FrozenBubble::Stuff:
    file: lib/Games/FrozenBubble/Stuff.pm
  Games::FrozenBubble::Symbols:
    file: lib/Games/FrozenBubble/Symbols.pm
requires:
  Alien::SDL: 1.403
  Carp: 0
  Data::Dumper: 0
  DynaLoader: 0
  Errno: 0
  Fcntl: 0
  File::Glob: 0
  File::ShareDir: 1.00
  Getopt::Long: 0
  IO::Socket: 1.24
  Locale::Maketext::Simple: 0
  Math::Trig: 0
  POSIX: 0
  SDL: 2.405
  SDLx::TTF: 0
  Time::HiRes: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://sdlperl.ath.cx/projects/SDLPerl/query?component=FrozenBubble
  license: http://opensource.org/licenses/gpl-2.0.php
  repository: http://github.com/kthakore/frozen-bubble
version: 2.202
